drop table if exists account;
drop table if exists transaction;
drop table if exists users;


create table users
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL
);
create table account
(
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance   DECIMAL(10, 2) NOT NULL,
    host_id  int references users (id)
);

CREATE TABLE transaction
(
    id                  INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount              DECIMAL(10, 2) NOT NULL,
    timestamp           TIMESTAMP      NOT NULL,
    sender_account_id   INT            NOT NULL,
    receiver_account_id INT            NOT NULL,
    FOREIGN KEY (sender_account_id) REFERENCES account (id) ,
    FOREIGN KEY (receiver_account_id) REFERENCES account (id)
);
